// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {valorantapi} from '../models';

export function CloseWindow():Promise<void>;

export function DeleteSavedLoadout(arg1:string):Promise<void>;

export function GetLoadout():Promise<main.SavedLoadout>;

export function GetLoadouts():Promise<void>;

export function GetMatch():Promise<valorantapi.MatchData>;

export function LoadSavedLoadout(arg1:string):Promise<void>;

export function MinimizeWindow():Promise<void>;

export function SaveCurrentLoadout(arg1:string):Promise<void>;

export function SelectRandomAgent():Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function UpdateCurrentClient():Promise<void>;
