// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteSavedLoadout(arg1) {
  return window['go']['main']['App']['DeleteSavedLoadout'](arg1);
}

export function ExitCoreGame() {
  return window['go']['main']['App']['ExitCoreGame']();
}

export function ExitPregame() {
  return window['go']['main']['App']['ExitPregame']();
}

export function GetLoadout() {
  return window['go']['main']['App']['GetLoadout']();
}

export function GetLoadouts() {
  return window['go']['main']['App']['GetLoadouts']();
}

export function GetMatch() {
  return window['go']['main']['App']['GetMatch']();
}

export function LoadSavedLoadout(arg1) {
  return window['go']['main']['App']['LoadSavedLoadout'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function SaveCurrentLoadout(arg1) {
  return window['go']['main']['App']['SaveCurrentLoadout'](arg1);
}

export function SelectRandomAgent() {
  return window['go']['main']['App']['SelectRandomAgent']();
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function UpdateCurrentClient() {
  return window['go']['main']['App']['UpdateCurrentClient']();
}
