// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {valorantapi} from '../models';

export function AddWeaponsToBeRandomized(arg1:Record<string, boolean>):Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteSavedLoadout(arg1:string):Promise<void>;

export function DownloadInstaller():Promise<string>;

export function ExitCoreGame():Promise<void>;

export function ExitPregame():Promise<void>;

export function GetLoadout():Promise<main.SavedLoadout>;

export function GetLoadouts():Promise<main.UpdateLoadoutObj>;

export function GetMatch():Promise<valorantapi.MatchData>;

export function GetSettings():Promise<Record<string, boolean>>;

export function LoadSavedLoadout(arg1:string,arg2:boolean):Promise<void>;

export function MinimizeWindow():Promise<void>;

export function SaveCurrentLoadout(arg1:string):Promise<void>;

export function SaveSettings(arg1:Record<string, boolean>):Promise<void>;

export function SelectRandomAgent():Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function StartUpdate():Promise<void>;

export function UpdateCurrentClient():Promise<void>;

export function UpdateSettings():Promise<void>;
